### ISSUE TITLE
Upload Indian wordlist for WPA cracking

### ISSUE THREAD

**Issue by 404notfound-creator** [zxcV32/indian-wordlist#7]
Can you upload another Indian wordlist(8-20) for WPA cracking.
If can you can please upload compressed with 7zip .
Thanks

**Comment by zxcV32** [comment]
Thanks for the suggestion. Please check the latest commit.

https://github.com/zxcV32/indian-wordlist/blob/master/indian-passwords-length8-20
https://github.com/zxcV32/indian-wordlist/blob/master/indian-passwords-length8-20-sorted

**Comment by 404notfound-3** [comment]
Thanks, @zxcV32
